-- Pagila DB Documentation
-- DO NOT EDIT THIS FILE; SEE dbdoc.org FILE

COMMENT ON TABLE film IS 'A film, aka movie, is released initially in theaters, and then available to movie /stores/, at which point they become available to the DB.';
--;;
COMMENT ON COLUMN film.title IS 'The full name of the film, including things like sub-title and part in a series; does not include language';
--;;
COMMENT ON COLUMN film.description IS 'A brief synopsis (catchy prose) about the plot';
--;;
COMMENT ON COLUMN film.original_language IS 'Spoken language, defaults to English';
--;;
COMMENT ON COLUMN film.rental_rate IS 'The price in US dollars and cents the /store/ charges for a short-duration rental';
--;;
COMMENT ON COLUMN film.length IS 'Duration in minutes of the film; does not include any previews';
--;;
COMMENT ON COLUMN film.rating IS 'MPAA rating: G, PG, PG-13, R, etc';
--;;

COMMENT ON TABLE actor IS 'An actor is very simple and non-comprehinsive table to record the main headlining /stars/ of the film. All fields are obvious. Note that there may be duplicate actors that use slightly different names on occasion.';
--;;

COMMENT ON TABLE customer IS 'A movie store patron. A customer visits the store to rent a movie. We register them as a customer when they rent their first film.';
--;;
COMMENT ON COLUMN customer.activebool IS 'A true value indicated that they have successfully rented at least one movie. Also set to =false= after 3 years of not renting any movie.';
--;;
COMMENT ON COLUMN customer.create_date IS 'The date that the customer creates an account; may be different from first rental date';
--;;

COMMENT ON TABLE rental IS 'An instance of a film being rented from the /store/. Note that a delinquent customer will not be allowed to create a new rental. #hot';
--;;
COMMENT ON COLUMN rental.return_date IS 'The date that a film is returned to the store in a valid state, which means properly rewound and in good working condition';
--;;
COMMENT ON COLUMN rental.rental_date IS 'The date at which a customer rents a movie';
--;;
